# Generated by Django 3.1.4 on 2021-01-06 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
