# Generated by Django 3.1.5 on 2021-01-06 08:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210106_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 8, 38, 17, 87976, tzinfo=utc)),
        ),
    ]
