# Generated by Django 3.1.5 on 2021-01-06 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
