# Generated by Django 3.1.4 on 2021-01-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home', 'Home'), ('other', 'Other'), ('toys', 'Toys'), ('undefined', 'Undefined')], default='undefined', max_length=20),
        ),
    ]
