# Generated by Django 3.1.4 on 2021-01-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210107_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='listings',
            field=models.ManyToManyField(related_name='categories', to='auctions.Listing'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home', 'Home'), ('other', 'Other'), ('toys', 'Toys')], default='other', max_length=20),
        ),
    ]
