# Generated by Django 3.1.4 on 2021-01-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210110_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[(1, 'Electronics'), (2, 'Fashion'), (3, 'Home'), (4, 'Other'), (5, 'Toys')], default=4, max_length=20),
        ),
    ]
