# Generated by Django 3.1.4 on 2021-01-11 16:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8),
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='bid',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
