# Generated by Django 3.1.4 on 2021-01-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20210111_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listings',
            field=models.ManyToManyField(related_name='users', to='auctions.Listing'),
        ),
    ]
