# Generated by Django 3.2.5 on 2021-07-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20210707_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='user_id',
            new_name='user',
        ),
    ]
