# Generated by Django 3.2.5 on 2021-07-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auto_20210707_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='current_bid',
            new_name='bid',
        ),
    ]
